#version: '3.8'

services:
  jmeter-master:
    build: .
    container_name: jmeter-master
    environment:
      - MODE=MASTER
    volumes:
      - ./scripts:/scripts
      - ./configs:/configs
      - ./results:/results
    networks:
      - jmeter-net
    ports:
      - "60000:60000"

  jmeter-slave:
    build: .
    environment:
      - MODE=SLAVE
    networks:
      - jmeter-net
    ports:
      - "1099"
      - "50000"
    # Use deploy for scaling (works with docker-compose up --scale)
    deploy:
      mode: replicated
      replicas: 2

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    environment:
      - INFLUXDB_DB=jmeter
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    networks:
      - jmeter-net
    ports:
      - "8086:8086"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - jmeter-net
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

networks:
  jmeter-net:
    driver: bridge
